### ISSUE TITLE
What do professional developers do during working hours

### ISSUE THREAD

**Issue by ShaolinSarg** [FP-North-East/session-proposals#2]
Prior to the session if everyone could come up with a 3-5 minute piece about what they do as a jobbing software developer

**Comment by ShaolinSarg** [comment]
David Sarginson will talk about working for Opencast software working at HMRC

**Comment by ajkavanagh** [comment]
Sure; I might need a reminder, though. :)

**Comment by darrenjw** [comment]
Given our meetup topic, I guess it would be particularly interesting to know how ideas from functional programming are used in practice (if at all!).

**Comment by ShaolinSarg** [comment]
scheduled for june

**Comment by DavidGregory084** [comment]
Happy to talk about what I do at JHC and how we use Scala

**Comment by DavidGregory084** [comment]
https://www.meetup.com/FP-North-East/events/249864523/
